"""Add rock_id and resolution fields to EvidenceRelation

Revision ID: 375bbe389ce2
Revises: f92cad3b62f7
Create Date: 2026-09-29 19:52:22.872011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '375bbe389ce2'
down_revision: Union[str, None] = 'f92cad3b62f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evidence_relations', sa.Column('rock_id', sa.String(), nullable=True))
    op.add_column('evidence_relations', sa.Column('is_resolved', sa.Integer(), nullable=True))
    op.add_column('evidence_relations', sa.Column('resolution_note', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'evidence_relations', 'rocks', ['rock_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'evidence_relations', type_='foreignkey')
    op.drop_column('evidence_relations', 'resolution_note')
    op.drop_column('evidence_relations', 'is_resolved')
    op.drop_column('evidence_relations', 'rock_id')
    # ### end Alembic commands ###
