"""Update Den and Add JoinRequest

Revision ID: bb8df0456a2b
Revises: f1206fa90de8
Create Date: 2026-09-29 15:16:16.189409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb8df0456a2b'
down_revision: Union[str, None] = 'f1206fa90de8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('join_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('den_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['den_id'], ['dens.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('dens', sa.Column('is_public', sa.String(), nullable=True))
    op.add_column('dens', sa.Column('invite_code', sa.String(), nullable=True))
    op.add_column('dens', sa.Column('max_members', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dens', 'max_members')
    op.drop_column('dens', 'invite_code')
    op.drop_column('dens', 'is_public')
    op.drop_table('join_requests')
    # ### end Alembic commands ###
